

spring:
  application:
    name: csstore-microservice

server:
  port: 9001
  #context-path: /csstore
eureka:
  client:
    serviceUrl:      
       defaultZone: http://localhost:9000/eureka
    register-with-eureka: true
    fetch-registry: true